import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { it } from 'node:test'
import { pathToFileURL } from 'node:url'
import { parse, stringify } from 'yaml'
import { checkConfig } from '../src/config/check.ts'
import composeConfig from '../src/config/compose.ts'

it('keeps compact named anchors and the configured section order without changing effective configuration', () => {
  const actual = readFileSync(new URL('../config/config.yaml', import.meta.url), 'utf8')
  const expected: Record<string, unknown> = {}
  for (const name of ['providerset.yaml', 'header.yaml', 'proxyset.yaml', 'routing.yaml']) {
    Object.assign(expected, parse(readFileSync(new URL(`../config/${name}`, import.meta.url), 'utf8'), { merge: true }))
  }
  assert.deepEqual(parse(actual, { merge: true }), expected)
  assert.match(actual, /ph: &ph \{ type: http,.*health-check: \{ enable:/)
  assert.match(actual, /provider1:\n\s+<<: \*ph/)
  assert.match(actual, /preferred_proxy: &preferred_proxy \{ type: select, proxies: \[\S.*\S\] \}/)
  assert.match(actual, /filter: \*hk/)
  assert.match(actual, /<<: \*classical/)
  const providers = actual.indexOf('\nproxy-providers:')
  const header = actual.indexOf('\nmixed-port:')
  const groups = actual.indexOf('\nproxy-groups:')
  const rules = actual.indexOf('\nrule-providers:')
  assert(actual.startsWith('anchor-provider:\n'))
  assert(providers >= 0 && providers < header && header < groups && groups < rules)
  assert(!actual.includes('Generated by pnpm'))
  assert(!actual.includes('修改后运行'))
})

it('rereads fragments and validates DNS references from the current configuration', async (t) => {
  const directory = await mkdtemp(join(tmpdir(), 'clash-config-test-'))
  t.after(() => rm(directory, { recursive: true, force: true }))
  const url = pathToFileURL(`${directory}/`)
  await writeFile(new URL('providerset.yaml', url), 'proxy-providers: {}\n')
  await writeFile(new URL('proxyset.yaml', url), 'proxy-groups: []\n')
  await writeFile(new URL('routing.yaml', url), stringify({
    'rule-providers': Object.fromEntries(['first', 'second', 'third'].map(name => [name, { behavior: 'domain', format: 'text' }])),
    'rules': [],
  }))
  for (const { policy, filter, error } of [
    { policy: 'rule-set:first,second', filter: 'rule-set:third', error: undefined },
    { policy: 'rule-set:missing-policy', filter: 'rule-set:third', error: /Missing DNS ruleset: missing-policy/ },
    { policy: 'rule-set:toString', filter: 'rule-set:third', error: /Missing DNS ruleset: toString/ },
    { policy: 'rule-set:first', filter: 'rule-set:missing-filter', error: /Missing DNS ruleset: missing-filter/ },
  ]) {
    await writeFile(new URL('header.yaml', url), stringify({
      dns: { 'nameserver-policy': { [policy]: ['1.1.1.1'] }, 'fake-ip-filter': [filter] },
    }))
    await writeFile(new URL('config.yaml', url), composeConfig(url).toString())
    if (error)
      assert.throws(() => checkConfig(url), error)
    else
      checkConfig(url)
  }
})
