import type { Behavior, BuildOptions, BuildResult, Rule, RulesetOutput } from './types.ts'
import { execFile } from 'node:child_process'
import { mkdir, mkdtemp, readdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, isAbsolute, join, relative, resolve } from 'node:path'
import process from 'node:process'
import { promisify } from 'node:util'
import { deduplicateRules, parseEntries, parseSource, removeRules, renderRule } from './rules.ts'

const execute = promisify(execFile)
const generator = 'clash-ruleset'

function compareRules(a: Rule, b: Rule): number {
  return a.text < b.text ? -1 : a.text > b.text ? 1 : 0
}

function render(lines: readonly string[]): string {
  return lines.length ? `${lines.join('\n')}\n` : ''
}

async function checkOutput(outDir: string): Promise<boolean> {
  const cwdRelative = relative(outDir, process.cwd())
  if (!cwdRelative || (!cwdRelative.startsWith('..') && !isAbsolute(cwdRelative)) || basename(outDir) === '.git')
    throw new Error('Output must not be the workspace, an ancestor, or a Git directory')
  let entries: string[]
  try {
    entries = await readdir(outDir)
  }
  catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT')
      return false
    throw error
  }
  if (entries.length) {
    try {
      const manifest: unknown = JSON.parse(await readFile(join(outDir, 'manifest.json'), 'utf8'))
      if (!manifest || typeof manifest !== 'object' || !('generator' in manifest) || manifest.generator !== generator)
        throw new Error('Not a generated directory')
    }
    catch (cause) {
      throw new Error('Refusing to replace an output directory not generated by clash-ruleset', { cause })
    }
  }
  return true
}

export async function build(options: BuildOptions): Promise<BuildResult> {
  const outDir = resolve(options.outDir ?? '.output')
  const names = options.rulesets.map(ruleset => ruleset.name)
  if (new Set(names).size !== names.length)
    throw new Error('Duplicate ruleset names')
  // 同时保护直接传入的普通 TS 对象，不只依赖工厂函数。
  if (names.some(name => !/^[a-z0-9][a-z0-9_-]*$/.test(name)))
    throw new Error('Invalid ruleset name')
  // 预留完整集合和全部分区名，避免新增分区或调整分类顺序后互相覆盖。
  const owners = new Map<string, string>()
  for (const name of names) {
    for (const suffix of ['', '-domain', '-ip', '-classical']) {
      const filename = `${name}${suffix}.txt`
      const owner = owners.get(filename)
      if (owner !== undefined)
        throw new Error(`Output filename collision: ${filename} (${owner}, ${name})`)
      owners.set(filename, name)
    }
  }
  const hadOutput = await checkOutput(outDir)
  await mkdir(dirname(outDir), { recursive: true })
  const staging = await mkdtemp(join(dirname(outDir), `${basename(outDir)}-`))
  const downloads = new Map<string, Promise<string>>()
  const outputs: RulesetOutput[] = []
  const mrs = options.mrs ?? true

  async function download(url: string): Promise<string> {
    let pending = downloads.get(url)
    if (!pending) {
      pending = (async () => {
        const response = await fetch(url, { signal: AbortSignal.timeout(options.timeoutMs ?? 30_000) })
        if (!response.ok)
          throw new Error(`Source returned HTTP ${response.status}`)
        return response.text()
      })()
      downloads.set(url, pending)
    }
    return pending
  }

  try {
    for (const ruleset of options.rulesets) {
      const removals = parseEntries(ruleset.remove, ruleset.name, 'remove')
      const additions = parseEntries(ruleset.add, ruleset.name, 'add')
      const groups = await Promise.all((ruleset.sources ?? []).map(async (source, index) => {
        try {
          return parseSource(await download(source.url), source)
        }
        catch (cause) {
          throw new Error(`Failed to load ${ruleset.name} source ${index + 1}`, { cause })
        }
      }))
      const rules = [...removeRules(groups.flat(), removals), ...additions]
        .filter(rule => ruleset.filter?.(rule) ?? true)
      const unique = deduplicateRules(rules).sort(ruleset.sort ?? compareRules)
      const output: RulesetOutput = {
        name: ruleset.name,
        count: unique.length,
        readable: `${ruleset.name}.txt`,
        files: {},
      }
      await writeFile(join(staging, output.readable), render(unique.map(rule => rule.text)))
      for (const behavior of ['domain', 'ipcidr', 'classical'] satisfies Behavior[]) {
        const entries = unique.filter(rule => rule.behavior === behavior)
        if (!entries.length)
          continue
        const suffix = behavior === 'ipcidr' ? 'ip' : behavior
        const text = `${ruleset.name}-${suffix}.txt`
        await writeFile(join(staging, text), render(entries.map(rule => renderRule(rule, behavior))))
        const file = { behavior, count: entries.length, text, ...(mrs && behavior !== 'classical' ? { mrs: `${ruleset.name}-${suffix}.mrs` } : {}) }
        if (file.mrs) {
          try {
            await execute(options.mihomo ?? 'mihomo', ['convert-ruleset', behavior, 'text', join(staging, text), join(staging, file.mrs)], { timeout: 30_000 })
          }
          catch (cause) {
            throw new Error(`MRS conversion failed for ${ruleset.name}/${behavior}`, { cause })
          }
        }
        output.files[behavior] = file
      }
      outputs.push(output)
    }
    await writeFile(join(staging, 'manifest.json'), `${JSON.stringify({ generator, rulesets: outputs }, null, 2)}\n`)
    // 全部转换成功后才替换旧产物；避免失败构建留下半套新规则。
    const previous = join(staging, '.previous')
    if (hadOutput)
      await rename(outDir, previous)
    try {
      await rename(staging, outDir)
    }
    catch (error) {
      if (hadOutput)
        await rename(previous, outDir)
      throw error
    }
    if (hadOutput)
      await rm(join(outDir, '.previous'), { recursive: true, force: true })
    return { outDir, rulesets: outputs }
  }
  finally {
    await rm(staging, { recursive: true, force: true })
  }
}
